# Generated by Django 5.0.7 on 2024-08-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie_id',
            field=models.CharField(max_length=255),
        ),
    ]
